// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0J4L9ZrDx1QmSZHfvEGIPU6vdQC-73t0',
    appId: '1:915303182974:web:6011202c688a1fd286de2f',
    messagingSenderId: '915303182974',
    projectId: 'dispenser-56c3f',
    authDomain: 'dispenser-56c3f.firebaseapp.com',
    databaseURL: 'https://dispenser-56c3f-default-rtdb.firebaseio.com',
    storageBucket: 'dispenser-56c3f.firebasestorage.app',
    measurementId: 'G-L95Z9D9H05',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3fac8eV3lspf9o05EOC6E4CbilOnNDJM',
    appId: '1:915303182974:android:49c2879b85ac277c86de2f',
    messagingSenderId: '915303182974',
    projectId: 'dispenser-56c3f',
    databaseURL: 'https://dispenser-56c3f-default-rtdb.firebaseio.com',
    storageBucket: 'dispenser-56c3f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbZzUqlWbRhmNOtL2n95kNSBDUkR6wz6U',
    appId: '1:915303182974:ios:7b6c4ec079f5335c86de2f',
    messagingSenderId: '915303182974',
    projectId: 'dispenser-56c3f',
    databaseURL: 'https://dispenser-56c3f-default-rtdb.firebaseio.com',
    storageBucket: 'dispenser-56c3f.firebasestorage.app',
    iosBundleId: 'com.example.dispenser',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbZzUqlWbRhmNOtL2n95kNSBDUkR6wz6U',
    appId: '1:915303182974:ios:7b6c4ec079f5335c86de2f',
    messagingSenderId: '915303182974',
    projectId: 'dispenser-56c3f',
    databaseURL: 'https://dispenser-56c3f-default-rtdb.firebaseio.com',
    storageBucket: 'dispenser-56c3f.firebasestorage.app',
    iosBundleId: 'com.example.dispenser',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0J4L9ZrDx1QmSZHfvEGIPU6vdQC-73t0',
    appId: '1:915303182974:web:b3054281b5faa30c86de2f',
    messagingSenderId: '915303182974',
    projectId: 'dispenser-56c3f',
    authDomain: 'dispenser-56c3f.firebaseapp.com',
    databaseURL: 'https://dispenser-56c3f-default-rtdb.firebaseio.com',
    storageBucket: 'dispenser-56c3f.firebasestorage.app',
    measurementId: 'G-YQBSVFXHSC',
  );
}
